### ISSUE TITLE
Auto-complete works in REPL but not in file

### ISSUE THREAD

**Issue by kureta** [sjlevine/atom-slime#15] opened 2016-03-02 02:51 UTC
Atom does not suggest auto-compilation for anything in file. But it works great in REPL. Is this an atom limitation? Code highlighting id also a bit off. [Here is an image.](http://i.imgur.com/8jWG4AX.png)

**Comment by sjlevine** [comment] 2016-03-02 03:33
I get autocomplete for certain things in Lisp files, but it looks not for everything that would be nice to add, and is just a bug (not a known limitation).

Also what is wrong with the code highlighting in your picture?

**Comment by kureta** [comment] 2016-03-03 03:41
I expected function names to be blue like it is at the first line in ```(defun fast-factorial-aux...```

By the way, thank you very much for saving me from emacs :)

**Comment by sjlevine** [comment] 2016-07-25 20:43
Hi again, are you still getting no auto-completion? If not, I'm going to close this issue shortly. Things seem to be working on my end.

As far as the syntax highlighting of auto-completed function names, there's no support for that at the moment, but I agree it would be neat. Feel free to dive into the code and submit a pull request!

**Comment by sjlevine** [comment] 2016-12-23 18:03
Going to close this issue now. Feel free to re-open if you're still having an issue. Thanks!

**Closed by sjlevine** 2016-12-23 18:03 UTC
Labels: enhancement, help wanted

**Comment by stykhanskyy** [comment] 2017-04-05 03:15
I have the same problem. After short debugging in Atom dev tools I found that root cause is code  `(@repl?.prompt?.length or 0)` in slime-autocomplete.coffee.

What is basically happening is `@repl?.prompt?.length` returns 9 (length of "CL-USER> " in REPL) which is the right thing to do in REPL, but it also returns 9 when in editor. As a result, first 9 characters of the autocomplete line are being removed so if the autocompleted keyword starts within first 9 characters autocomplete won't work, if after - it will work.

I'd send a patch, but not sure how to fix it since I'm very new to both Atom plugins development and atom-slime.

**Comment by stykhanskyy** [comment] 2017-04-05 03:23
When I replaced `(@repl?.prompt?.length or 0)` with `0` and restarted Atom autocomplete started working everywhere (in both REPL and editor).

**Comment by sjlevine** [comment] 2017-04-07 18:35
Thanks for looking into this and delving into the code!

I seem to be having trouble reproducing this. If you wouldn't mind, could you please send me a short file to help me debug? I.e., a Common Lisp function, and where to put the cursor, where to type, and what you should expect to happen. 

Thanks!

**Comment by stykhanskyy** [comment] 2017-04-10 01:41
I attached screenshots of what is happening (see description of screenshots below).

But I highly suspect that the issue is surfacing only in some environments, because when the issue is happening, it is so obvious that you'd definitely notice it just by using the plugin. Maybe there's some interference with another Atom plugin or even plugin+version.

Screenshots description:

1 - when I press space - nothing is happening:
<img width="784" alt="1 - no-autocomplete" src="https://cloud.githubusercontent.com/assets/1272643/24842973/07df9084-1d53-11e7-9328-df322596aacb.png">

2 - when I press space, autocomplete shows up, but it is incorrect because it offsets string by 9 characters and starts autocomplete only from 10th character:
<img width="784" alt="2 - incorrect-autocomplete" src="https://cloud.githubusercontent.com/assets/1272643/24842977/0a363fea-1d53-11e7-81de-cfd2cf3694a0.png">

3 - if I move (read-line) past 9th character - autocomplete is working properly:
<img width="787" alt="3 - correct-autocomplete" src="https://cloud.githubusercontent.com/assets/1272643/24842796/1b5eeb34-1d51-11e7-8125-794e1f3f0b63.png">

Since this is probably environment related and you likely won't be able to reproduce the issue, I'll try to debug it myself of my machine.

**Comment by sjlevine** [comment] 2017-04-10 15:06
Ahh, I see what you mean. I am indeed able to reproduce this on my machine. Thanks for taking the time to put together such a clear and detailed response. I'll have a fix out shortly.

**Comment by sjlevine** [comment] 2017-04-10 15:13
This should be fixed now as of  `atom-slime` v2.8.0. Please let me know if you have any more issues, thanks again!

**Comment by sjlevine** [comment] 2017-04-10 15:15
Also, one more thing to note: I've updated the documentation slightly to work better with auto completion if you're using the `lisp-paredit` package and intending automatically with the tab key. See the slightly-updated code to add to your atom init file in step 5 of the guide to setting up lisp with atom.
