### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by dragosboca** [sjlevine/atom-slime#8] opened 2015-12-17 13:21 UTC
[Enter steps to reproduce below:]

1. connect to swank server
2. enter an expression that produce an error - like (error "error"). 

**Atom Version**: 1.3.2
**System**: "Fedora release
**Thrown From**: [atom-slime](https://github.com/sjlevine/atom-slime) package, v1.7.2

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /usr/share/atom/resources/app.asar/src/pane.js:620

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app.asar/src/pane.js:620:15)
    at REPLView.module.exports.REPLView.showDebugTab (/home/dboca/.atom/packages/atom-slime/lib/atom-slime-repl-view.coffee:213:15)
    at Object.debug_activate (/home/dboca/.atom/packages/atom-slime/lib/atom-slime-repl-view.coffee:162:7)
    at Client.debug_activate_handler (/home/dboca/.atom/packages/atom-slime/node_modules/swank-client-js/lib/client.js:316:20)
    at Client.on_swank_message (/home/dboca/.atom/packages/atom-slime/node_modules/swank-client-js/lib/client.js:150:10)
    at Client.data_complete_callback (/home/dboca/.atom/packages/atom-slime/node_modules/swank-client-js/lib/client.js:127:8)
    at Client.socket_data_handler (/home/dboca/.atom/packages/atom-slime/node_modules/swank-client-js/lib/client.js:107:14)
    at Socket.<anonymous> (/home/dboca/.atom/packages/atom-slime/node_modules/swank-client-js/lib/client.js:71:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

### Commands

```
     -0:27.8.0 release-notes:show (div.panels-item)
     -0:10.5.0 slime:connect (div.release-notes.padded.pane-item.native-key-bindings)
     -0:01.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:00.8.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-perl"
    ]
  },
  "atom-slime": {}
}
```

### Installed Packages

```coffee
# User
atom-perl-prove, v0.5.0
atom-slime, v1.7.2
atom-terminal-panel, v4.4.4
css-color-underline, v1.0.1
language-lisp, v0.1.2
linter, v1.11.3
lisp-paredit, v0.5.1
perltidy, v2.2.0

# Dev
No dev packages
```

**Comment by sjlevine** [comment] 2016-01-20 06:40
Hello @dragosboca, I unfortunately haven't been able to reproduce this error on my computer. When I run `(error "error")` at a REPL, the debugger pane correctly pops up.

Could you please try updating to the latest version of `atom-slime`, making sure it's installed correctly (see the readme or the package preferences), and trying again? Thanks!

Cheers,
Steve

**Comment by sjlevine** [comment] 2016-02-04 22:58
Going to close this since I can't reproduce.

**Closed by sjlevine** 2016-02-04 22:58 UTC
